### ISSUE TITLE
Where do I find import com.dap.routines.basic.SystemRoutines? 

### ISSUE THREAD

**Issue by rezacsedu** [UnyieldingOrca/dl4j-rl#1]
Hi,

Where do I find import com.dap.routines.basic.SystemRoutines?

**Comment by UnyieldingOrca** [comment]
Hi rezacsedu,

That package references some common code I use while coding. I meant to take out those references when I uploaded the code :/ . The code I was referencing was just some simple error handling. I took out the dependency but haven't tested it. Feel free to give it a try. I'll be able to test it tomorrow.

**Comment by rezacsedu** [comment]
Hi @UnyieldingOrca,

Thanks for the clues. I removed the error handling part and managed to run the code, which probably generates the moves made by an agent to reach a numeric reward:

Episode: 99
0000
1000
0000
000-1

[[    0.0026,    0.0061,    0.1230,    0.0060]] 3
[[   -0.2051,   -0.1487,    0.2766,    0.1883]] 0
[[   -0.3329,   -0.0829,    0.1676,   -0.0127]] 2
[[   -0.4529,   -0.4157,    0.1441,    0.2226]] 1
[[   -0.5943,   -0.0495,    0.2015,    0.3354]] 1
[[   -0.6651,   -0.3208,    0.3811,    0.4580]] 1
[[   -0.9724,   -0.2239,    0.3422,    0.5410]] 0
[[   -0.9322,   -0.3478,    0.4714,    0.5868]] 0
00-10
0010
0000
0000

However, I was wondering if you have written any module for visualizing all the moves from source to target?

**Comment by UnyieldingOrca** [comment]
I don't have any module for a graphical representation of the game. The 0,1,-1 grid represents the map at each timestep. The numbers in brackets are just the outputs of the NN, followed by the index of the highest value.

**Comment by rezacsedu** [comment]
@UnyieldingOrca, 

Thanks a million for the clarification. Finally, I was wondering if I'm allowed to reuse some code from this repository for blogs, research or books? If so, how can I cite this source?
